"""init

Revision ID: e86e8902513f
Revises: 206a42f53477
Create Date: 2021-09-04 10:06:10.980766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86e8902513f'
down_revision = '206a42f53477'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
