"""init

Revision ID: 3b99af083f9e
Revises: e86e8902513f
Create Date: 2021-09-04 10:06:40.244840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b99af083f9e'
down_revision = 'e86e8902513f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
